# Generated by Django 3.0.3 on 2020-06-14 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocterInfo',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_account', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_sex', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_pwd', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_department', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_job', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor_tel', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'docter_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_sex', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_age', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_born', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_nation', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_address', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_job', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_allergy', models.CharField(blank=True, max_length=255, null=True)),
                ('p_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.DocterInfo')),
            ],
            options={
                'db_table': 'patient_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecordInfo',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_id', models.CharField(blank=True, max_length=255, null=True)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('record_slicer_file', models.CharField(blank=True, max_length=255, null=True)),
                ('record_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('record_opinion', models.CharField(blank=True, max_length=255, null=True)),
                ('r_p', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demo.PatientInfo')),
            ],
            options={
                'db_table': 'record_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ModelInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField()),
                ('model_file', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='demo.RecordInfo')),
            ],
            options={
                'db_table': 'model_info',
                'managed': True,
            },
        ),
    ]
